version: '3.8'

services:
  claude-dev:
    image: ${CLAUDE_DOCKER_IMAGE:-claude-code:latest}
    build: 
      context: .
      dockerfile: Dockerfile
    # container_name を削除してデフォルト名を使用
    user: "1000:1000"
    group_add:
      - "${DOCKER_GID:-999}"  # Auto-detected by dev.sh
    # privileged: true  # Removed for security
    volumes:
      # Mount projects directory
      - ./projects:/workspace/projects
      # Mount Claude configuration
      - ./claude-config:/home/developer/.claude
      # Mount Codex CLI configuration
      - ./codex-config:/home/developer/.codex
      # Mount Google Cloud configuration for Gemini CLI
      - $HOME/.config/gcloud:/home/developer/.config/gcloud:ro
      # Mount OpenAI configuration (for OpenAI/Codex related CLIs)
      - $HOME/.config/openai:/home/developer/.config/openai:ro
      # Mount cache directories
      # - ./cache:/home/developer/.cache  # Commented out to use container's own cache directory
      # Mount SSH keys if needed
      - ~/.ssh:/home/developer/.ssh:ro
      # Mount Docker socket for Docker-in-Docker
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount logs, coverage, and test results
      - ./logs:/workspace/logs
      - ./coverage:/workspace/coverage
      - ./test-results:/workspace/test-results
    environment:
      # API keys (optional). Prefer host-side credentials that are mounted/copied.
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT:-}
      # npm config
      - NPM_CONFIG_CACHE=/tmp/npm-cache
      - NPM_CONFIG_PREFIX=/home/developer/.npm-global
      # Database URLs
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/dev_db
      - REDIS_URL=redis://redis:6379
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "${HOST_PORT_FE:-3001}:3000"   # Frontend
      - "${HOST_PORT_BE:-4001}:4000"   # Backend API
      - "${HOST_PORT_MCP:-5001}:5000"  # MCP Server
    networks:
      - claude-net
    stdin_open: true
    tty: true
    working_dir: /workspace/projects
    depends_on:
      - postgres
      - redis
      - elasticsearch

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${HOST_PORT_PG:-5433}:5432"
    networks:
      - claude-net

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "${HOST_PORT_REDIS:-6380}:6379"
    networks:
      - claude-net

  elasticsearch:
    image: elasticsearch:8.11.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "${HOST_PORT_ES_HTTP:-9201}:9200"
      - "${HOST_PORT_ES_TRANSPORT:-9301}:9300"
    networks:
      - claude-net

networks:
  claude-net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  es_data:
