
version: '3.8'

services:
  claude-dev:
    image: ${CLAUDE_DOCKER_IMAGE:-claude-code:latest}
    build: 
      context: .
      dockerfile: Dockerfile
    # container_name を削除してデフォルト名を使用
    user: "1000:1000"
    volumes:
      # Mount projects directory
      - ./projects:/workspace/projects
      # Mount Claude configuration
      - ./claude-config:/home/developer/.claude
      # Mount cache directories
      - ./cache:/home/developer/.cache
      # Mount SSH keys if needed
      - ~/.ssh:/home/developer/.ssh:ro
      # Mount Docker socket for Docker-in-Docker
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # Set Claude API key from environment or .env file
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      # npm config
      - NPM_CONFIG_CACHE=/tmp/npm-cache
      - NPM_CONFIG_PREFIX=/home/developer/.npm-global
    networks:
      - claude-net
    stdin_open: true
    tty: true
    working_dir: /workspace/projects

networks:
  claude-net:
    name: claude-network
    driver: bridge