
services:
  claude-dev:
    build: .
    container_name: claude-dev-container
    volumes:
      # Mount projects directory (create if not exists)
      - ./projects:/workspace/projects
      # Mount Claude configuration
      - ./claude-config:/home/developer/.claude
      # Mount cache directories for persistence
      - ./cache:/home/developer/.cache
      - ./npm-cache:/home/developer/.npm
      # Mount SSH keys if needed
      - ~/.ssh:/home/developer/.ssh:ro
    environment:
      # Set Claude API key from environment or .env file
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
    stdin_open: true
    tty: true
    working_dir: /workspace/projects
    command: ["claude", "--dangerously-skip-permissions"]
    user: "1000:1000"